# auto-generated by OpenPlug.ai
try:
    from fastmcp import FastMCP
except ImportError:
    from mcp.server.fastmcp import FastMCP

import httpx
import os
import json
import logging
import time
from datetime import datetime, UTC
from typing import Optional, Dict, Any, List

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("Swagger Petstore")

mcp = FastMCP("Swagger Petstore")
BASE_URL = "https://petstore.swagger.io/v2"
SERVER_ID = "69d6efe9cbbd6fd71293d8f0"
HUB_API_URL = os.environ.get('HUB_API_URL', "https://backend.openplug.ai")


# --- Insight POST ------------------------------------------------------------
async def _post_insight(tool_name: str, status: str, duration_ms: float,
                        error: Optional[str] = None,
                        input_size: int = 0, output_size: int = 0):
    payload = {
        "server_id": SERVER_ID,
        "tool_name": tool_name,
        "request_type": "tool",
        "execution_time_ms": duration_ms,
        "status": status,
        "error": error,
        "input_size": input_size,
        "output_size": output_size,
        "timestamp": datetime.now(UTC).isoformat(),
    }
    _url = HUB_API_URL.rstrip('/') + '/api/insights/track'
    try:
        async with httpx.AsyncClient(timeout=5.0) as _c:
            _r = await _c.post(_url, json=payload)
            logger.info(f"[insight] {tool_name} {status} {duration_ms:.0f}ms -> HTTP {_r.status_code}")
    except Exception as _e:
        logger.warning(f"[insight] POST failed: {_e}")


# --- Auth Token Cache ---------------------------------------------------------
_token_cache = {}
_auth_profiles = []
_route_auth_mappings = []
_default_auth_profile_id = None

def _resolve_path(data, path):
    if not path:
        return None
    if not isinstance(data, (dict, list)):
        return None
    current = data
    token = ''
    i = 0
    while i < len(path):
        ch = path[i]
        if ch == '.':
            if token:
                if not isinstance(current, dict):
                    return None
                if token in current:
                    current = current[token]
                else:
                    key_map = {str(k).lower(): k for k in current.keys()}
                    match = key_map.get(token.lower())
                    if match is None:
                        return None
                    current = current[match]
                token = ''
            i += 1
            continue
        if ch == '[':
            if token:
                if not isinstance(current, dict):
                    return None
                if token in current:
                    current = current[token]
                else:
                    key_map = {str(k).lower(): k for k in current.keys()}
                    match = key_map.get(token.lower())
                    if match is None:
                        return None
                    current = current[match]
                token = ''
            j = path.find(']', i)
            if j == -1:
                return None
            idx_txt = path[i + 1:j]
            if not isinstance(current, list) or not idx_txt.isdigit():
                return None
            idx = int(idx_txt)
            if idx < 0 or idx >= len(current):
                return None
            current = current[idx]
            i = j + 1
            continue
        token += ch
        i += 1
    if token:
        if not isinstance(current, dict):
            return None
        if token in current:
            current = current[token]
        else:
            key_map = {str(k).lower(): k for k in current.keys()}
            match = key_map.get(token.lower())
            if match is None:
                return None
            current = current[match]
    return current

def _path_matches(pattern, path):
    if not pattern:
        return False
    if pattern == '*':
        return True
    if pattern.endswith('*'):
        return path.startswith(pattern[:-1])
    return path == pattern

def _select_auth_profile(method, path):
    if not _auth_profiles:
        return None
    _profiles_by_id = {str(p.get('id', '')): p for p in _auth_profiles if isinstance(p, dict)}
    for m in _route_auth_mappings or []:
        if not isinstance(m, dict):
            continue
        _m_method = str(m.get('method', 'ANY')).upper()
        _m_pattern = str(m.get('path_pattern', ''))
        _m_profile = str(m.get('profile_id', ''))
        if (_m_method == 'ANY' or _m_method == method.upper()) and _path_matches(_m_pattern, path):
            if _m_profile in _profiles_by_id:
                return _profiles_by_id[_m_profile]
    if _default_auth_profile_id and str(_default_auth_profile_id) in _profiles_by_id:
        return _profiles_by_id[str(_default_auth_profile_id)]
    if _route_auth_mappings:
        return None
    return _auth_profiles[0] if _auth_profiles else None

async def get_auth_headers(method='GET', path=''):
    global _token_cache
    headers = {}
    
    # 1. Base Headers (Env Vars & Static Keys)
    # This logic is injected based on user configuration
        headers["api_key"] = os.environ.get('API_KEY', "")
    headers["api_key"] = ""

    # 2. Dynamic Token Handling (with caching and auto-parsing)
    _selected_profile = _select_auth_profile(method, path)
    if _selected_profile:
        _t_url = _selected_profile.get('token_url')
        _t_enabled = bool(_selected_profile.get('token_auth_enabled', True)) and bool(_t_url)
        _t_auth_type = str(_selected_profile.get('token_auth_type', 'oauth2')).lower()
        _t_req_loc = str(_selected_profile.get('token_request_location', 'headers')).lower()
        _t_http_method = str(_selected_profile.get('token_http_method', 'POST')).upper()
        _t_env_pairs = _selected_profile.get('env_vars', {}) or {}
        _t_request_body = _selected_profile.get('token_request_body', {})
        _mapping = _selected_profile.get('token_mapping', {}) or {}
        _resp_key = _mapping.get('access_token') or str(_selected_profile.get('response_parsing', 'access_token') or 'access_token')
        _type_key = _mapping.get('token_type') or str(_selected_profile.get('token_type_key', '') or '')
        _expiry_key = _mapping.get('expires_in') or str(_selected_profile.get('expiry_key', '') or '')
        _profile_id = str(_selected_profile.get('id', 'default'))
    elif _auth_profiles:
        _t_url = None
        _t_enabled = False
        _t_auth_type = 'oauth2'
        _t_req_loc = 'headers'
        _t_http_method = 'POST'
        _t_env_pairs = {}
        _t_request_body = {}
        _mapping = {}
        _resp_key = 'access_token'
        _type_key = ''
        _expiry_key = ''
        _profile_id = 'default'
    else:
        _t_url = os.environ.get('TOKEN_URL', None)
        _t_enabled = str(os.environ.get('TOKEN_AUTH_ENABLED', 'false')).lower() in ('1', 'true', 'yes', 'on')
        _t_auth_type = os.environ.get('TOKEN_AUTH_TYPE', 'oauth2').lower()
        _t_req_loc = os.environ.get('TOKEN_REQUEST_LOCATION', 'headers').lower()
        _t_http_method = os.environ.get('TOKEN_HTTP_METHOD', 'POST').upper()
        _t_env_pairs = {}
        _t_request_body = {}
        _mapping = {}
        _resp_key = _mapping.get('access_token') or 'access_token'
        _type_key = _mapping.get('token_type') or ''
        _expiry_key = _mapping.get('expires_in') or ''
        _profile_id = 'default'
    if _t_http_method not in ('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'):
        _t_http_method = 'POST'
    if _t_enabled and _t_url:
        now = time.time()
        _cache_entry = _token_cache.get(_profile_id, {'token': None, 'type': 'Bearer', 'expiry': 0})
        # Check cache (give 30s buffer before expiry)
        if _cache_entry['token'] and _cache_entry['expiry'] > (now + 30):
            logger.info('[auth] Using cached token')
            if _t_auth_type == 'api_key':
                _api_hdr = os.environ.get('TOKEN_API_KEY_HEADER', 'api_key')
                headers[_api_hdr] = _cache_entry['token']
            else:
                headers['Authorization'] = f'{_cache_entry["type"]} {_cache_entry["token"]}'
            return headers

        logger.info(f'[auth] Fetching fresh token from {_t_url}')
        try:
            _auth_payload = {}
            _request_body = _t_request_body
            for _k, _v in _t_env_pairs.items():
                _auth_payload[_k] = os.environ.get(_k, _v)
            _token_headers = dict(headers)
            _token_req_kwargs = {'headers': _token_headers}
            if _t_req_loc == 'headers':
                _token_headers.update(_auth_payload)
                if _request_body not in ({}, None):
                    _token_req_kwargs['json'] = _request_body
            elif _t_req_loc == 'form':
                if isinstance(_request_body, dict):
                    _token_req_kwargs['data'] = {**_auth_payload, **_request_body}
                elif _request_body in ({}, None):
                    _token_req_kwargs['data'] = _auth_payload
                else:
                    _token_req_kwargs['data'] = _auth_payload
            elif _t_req_loc == 'json':
                if isinstance(_request_body, dict):
                    _token_req_kwargs['json'] = {**_auth_payload, **_request_body}
                elif _request_body in ({}, None):
                    _token_req_kwargs['json'] = _auth_payload
                else:
                    _token_req_kwargs['json'] = _request_body
            elif _t_req_loc == 'query':
                if isinstance(_request_body, dict):
                    _token_req_kwargs['params'] = {**_auth_payload, **_request_body}
                else:
                    _token_req_kwargs['params'] = _auth_payload
            async with httpx.AsyncClient(timeout=10.0) as _c:
                _resp = await _c.request(_t_http_method, _t_url, **_token_req_kwargs)
                _resp.raise_for_status()
                _data = _resp.json()
                
                _token = _resolve_path(_data, _resp_key) if _resp_key else None
                if _token is None:
                    _token = _resolve_path(_data, 'access_token') or _resolve_path(_data, 'token') or _resolve_path(_data, 'id_token')
                
                if _token:
                    _type = _resolve_path(_data, _type_key) if _type_key else None
                    if _type is None:
                        _type = _resolve_path(_data, 'token_type') or 'Bearer'
                    _expires_in = _resolve_path(_data, _expiry_key) if _expiry_key else None
                    if _expires_in is None:
                        _expires_in = _resolve_path(_data, 'expires_in') or 3600
                    try:
                        _expires_in = int(_expires_in)
                    except Exception:
                        _expires_in = 3600
                    _type = str(_type).capitalize()
                    
                    _cache_entry['token'] = _token
                    _cache_entry['type'] = _type
                    _cache_entry['expiry'] = now + _expires_in
                    _token_cache[_profile_id] = _cache_entry
                    
                    logger.info(f'[auth] Successfully parsed {_type} token. Expires in {_expires_in}s')
                    if _t_auth_type == 'api_key':
                        _api_hdr = os.environ.get('TOKEN_API_KEY_HEADER', 'api_key')
                        headers[_api_hdr] = str(_token)
                    else:
                        headers['Authorization'] = f'{_type} {_token}'
                else:
                    logger.warning(f'[auth] Token key not found in response: {list(_data.keys())}')
        except Exception as _e:
            logger.error(f'[auth] Token fetch/parse failed: {_e}')
            # Fallback to existing headers if fetch fails
            
    return headers


 


async def make_request(
    method: str, path: str,
    query_params: Optional[Dict] = None, body: Any = None,
    content_type: str = "application/json", extra_headers: Optional[Dict] = None,
):
    url = BASE_URL + path
    headers = await get_auth_headers(method, path)
    if extra_headers:
        headers.update(extra_headers)
    logger.info(f"{method} {url}")
    async with httpx.AsyncClient(timeout=30.0) as client:
        if query_params:
            query_params = {k: v for k, v in query_params.items() if v is not None}
        kwargs: Dict[str, Any] = {"headers": headers, "params": query_params}
        if body is not None and method.upper() not in ["GET", "DELETE"]:
            kwargs["data" if content_type == "multipart/form-data" else "json"] = body
        try:
            resp = await client.request(method, url, **kwargs)
            resp.raise_for_status()
            try:
                return resp.json()
            except Exception:
                return resp.text
        except httpx.HTTPStatusError as e:
            return {"error": f"API returned {e.response.status_code}", "details": e.response.text}
        except Exception as e:
            return {"error": str(e)}



async def _root_handler(request):
    from starlette.responses import JSONResponse
    try:
        tools_list = [t.name for t in getattr(mcp, '_tools', {}).values()]
    except Exception:
        tools_list = []
    return JSONResponse({'status': 'ready', 'server': getattr(mcp, 'name', 'mcp-server'),
                         'tools': tools_list, 'hub': HUB_API_URL})


@mcp.tool(name="uploadFile")
async def uploadFile(petId: int, additionalMetadata: Optional[str] = None, file: Optional[str] = None):
    'uploads an image'
    return await make_request(
        "POST",
        f"/pet/{petId}/uploadImage",
        query_params=None,
        body={ "additionalMetadata": additionalMetadata, "file": file },
        content_type="multipart/form-data",
        extra_headers={},
    )

@mcp.tool(name="addPet")
async def addPet(id: Optional[int] = None, category: Optional[Dict[str, Any]] = None, name: Optional[str] = None, photoUrls: Optional[List[Any]] = None, tags: Optional[List[Any]] = None, status: Optional[str] = None):
    'Add a new pet to the store'
    return await make_request(
        "POST",
        f"/pet",
        query_params=None,
        body={ "id": id, "category": category, "name": name, "photoUrls": photoUrls, "tags": tags, "status": status },
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="updatePet")
async def updatePet(id: Optional[int] = None, category: Optional[Dict[str, Any]] = None, name: Optional[str] = None, photoUrls: Optional[List[Any]] = None, tags: Optional[List[Any]] = None, status: Optional[str] = None):
    'Update an existing pet'
    return await make_request(
        "PUT",
        f"/pet",
        query_params=None,
        body={ "id": id, "category": category, "name": name, "photoUrls": photoUrls, "tags": tags, "status": status },
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="findPetsByStatus")
async def findPetsByStatus(status: str):
    'Multiple status values can be provided with comma separated strings'
    return await make_request(
        "GET",
        f"/pet/findByStatus",
        query_params={ "status": status },
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="findPetsByTags")
async def findPetsByTags(tags: str):
    'Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.'
    return await make_request(
        "GET",
        f"/pet/findByTags",
        query_params={ "tags": tags },
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="getPetById")
async def getPetById(petId: int):
    'Returns a single pet'
    return await make_request(
        "GET",
        f"/pet/{petId}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="updatePetWithForm")
async def updatePetWithForm(petId: int, name: Optional[str] = None, status: Optional[str] = None):
    'Updates a pet in the store with form data'
    return await make_request(
        "POST",
        f"/pet/{petId}",
        query_params=None,
        body={ "name": name, "status": status },
        content_type="multipart/form-data",
        extra_headers={},
    )

@mcp.tool(name="deletePet")
async def deletePet(petId: int):
    'Deletes a pet'
    return await make_request(
        "DELETE",
        f"/pet/{petId}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="getInventory")
async def getInventory():
    'Returns a map of status codes to quantities'
    return await make_request(
        "GET",
        f"/store/inventory",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="placeOrder")
async def placeOrder(id: Optional[int] = None, petId: Optional[int] = None, quantity: Optional[int] = None, shipDate: Optional[str] = None, status: Optional[str] = None, complete: Optional[bool] = None):
    'Place an order for a pet'
    return await make_request(
        "POST",
        f"/store/order",
        query_params=None,
        body={ "id": id, "petId": petId, "quantity": quantity, "shipDate": shipDate, "status": status, "complete": complete },
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="getOrderById")
async def getOrderById(orderId: int):
    'For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions'
    return await make_request(
        "GET",
        f"/store/order/{orderId}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="deleteOrder")
async def deleteOrder(orderId: int):
    'For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors'
    return await make_request(
        "DELETE",
        f"/store/order/{orderId}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="createUsersWithListInput")
async def createUsersWithListInput():
    'Creates list of users with given input array'
    return await make_request(
        "POST",
        f"/user/createWithList",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="getUserByName")
async def getUserByName(username: str):
    'Get user by user name'
    return await make_request(
        "GET",
        f"/user/{username}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="updateUser")
async def updateUser(username: str, id: Optional[int] = None, username_body: Optional[str] = None, firstName: Optional[str] = None, lastName: Optional[str] = None, email: Optional[str] = None, password: Optional[str] = None, phone: Optional[str] = None, userStatus: Optional[int] = None):
    'This can only be done by the logged in user.'
    return await make_request(
        "PUT",
        f"/user/{username}",
        query_params=None,
        body={ "id": id, "username": username_body, "firstName": firstName, "lastName": lastName, "email": email, "password": password, "phone": phone, "userStatus": userStatus },
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="deleteUser")
async def deleteUser(username: str):
    'This can only be done by the logged in user.'
    return await make_request(
        "DELETE",
        f"/user/{username}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="loginUser")
async def loginUser(username: str, password: str):
    'Logs user into the system'
    return await make_request(
        "GET",
        f"/user/login",
        query_params={ "username": username, "password": password },
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="logoutUser")
async def logoutUser():
    'Logs out current logged in user session'
    return await make_request(
        "GET",
        f"/user/logout",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="createUsersWithArrayInput")
async def createUsersWithArrayInput():
    'Creates list of users with given input array'
    return await make_request(
        "POST",
        f"/user/createWithArray",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="createUser")
async def createUser(id: Optional[int] = None, username: Optional[str] = None, firstName: Optional[str] = None, lastName: Optional[str] = None, email: Optional[str] = None, password: Optional[str] = None, phone: Optional[str] = None, userStatus: Optional[int] = None):
    'This can only be done by the logged in user.'
    return await make_request(
        "POST",
        f"/user",
        query_params=None,
        body={ "id": id, "username": username, "firstName": firstName, "lastName": lastName, "email": email, "password": password, "phone": phone, "userStatus": userStatus },
        content_type="application/json",
        extra_headers={},
    )

from starlette.applications import Starlette
from starlette.responses import JSONResponse, Response
from starlette.routing import Route
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request as _R

class _NoCacheMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        resp = await call_next(request)
        if request.url.path in ("/sse", "/messages", "/messages/"):
            resp.headers["Cache-Control"] = "no-cache"
            resp.headers["Connection"] = "keep-alive"
            resp.headers["X-Accel-Buffering"] = "no"
        return resp

class _HubSecurityMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        # Allow health checks and root
        if request.url.path in ("/", "/health"):
            return await call_next(request)
        
        # Check for openplug.ai Key in Header or Query Param
        hub_key = request.headers.get("X-openplug.ai-Key") or request.query_params.get("apikey")
        
        # Allow THE Hub's internal key (for insights and management)
        if hub_key == "openplug.ai_internal_access":
            return await call_next(request)
        
        # Check for valid key
        if not hub_key:
            return JSONResponse({"error": "Unauthorized: Missing X-openplug.ai-Key (Hub Bypass Detected)"}, status_code=401)
            
        return await call_next(request)

try:
    from mcp.server.sse import SseServerTransport
    _transport = SseServerTransport("/messages/")

    # GET /sse — SSE streaming endpoint
    async def _sse_endpoint(request: _R):
        _inner = getattr(mcp, '_mcp_server', None) or getattr(mcp, 'server', None) or mcp
        async with _transport.connect_sse(request.scope, request.receive, request._send) as (r, w):
            await _inner.run(r, w, _inner.create_initialization_options(), raise_exceptions=False)
        return Response()

    # POST /sse — Streamable HTTP (direct tool dispatch, no SSE overhead)
    async def _sse_post_endpoint(request: _R):
        raw = await request.body()
        try:
            body = json.loads(raw)
            method = body.get("method")
            if method == "initialize":
                return JSONResponse({
                    "server": getattr(mcp, "name", "mcp-server"),
                    "capabilities": {"tools": True, "resources": False, "prompts": False}
                })
            elif method == "tools/list":
                tools_list = []
                try:
                    for t in getattr(mcp, "_tools", {}).values():
                        tools_list.append({"name": t.name, "description": getattr(t, "description", "")})
                except Exception:
                    pass
                return JSONResponse({"tools": tools_list})
            elif method == "tools/call":
                params = body.get("params", {})
                name = params.get("name")
                args = params.get("arguments", {})
                _start = time.perf_counter()
                _status, _error = "success", None
                try:
                    sanitized = "".join(c if c.isalnum() else "_" for c in name)
                    if sanitized and sanitized[0].isdigit():
                        sanitized = "t_" + sanitized
                    tool_fn = globals().get(sanitized)
                    if tool_fn:
                        res = await tool_fn(**args)
                        return JSONResponse({"content": [{"type": "text", "text": str(res)}]})
                    else:
                        raise ValueError(f"Tool '{name}' not found")
                except Exception as e:
                    _status, _error = "error", str(e)
                    return JSONResponse({"isError": True, "content": [{"type": "text", "text": str(e)}]})
                finally:
                    _dur = (time.perf_counter() - _start) * 1000
                    await _post_insight(name or "unknown", _status, _dur, _error, len(raw), 0)
            return JSONResponse({"error": "Unsupported method"}, status_code=400)
        except Exception as e:
            return JSONResponse({"error": str(e)}, status_code=500)

    # POST /messages — raw SSE transport handler
    async def _messages_endpoint(request: _R):
        raw = await request.body()
        _start = time.perf_counter()
        _tool_name, _is_tool_call = None, False
        try:
            _msgs = json.loads(raw)
            if isinstance(_msgs, dict):
                _msgs = [_msgs]
            for _m in _msgs:
                if _m.get("method") == "tools/call":
                    _is_tool_call = True
                    _tool_name = (_m.get("params") or {}).get("name", "unknown")
                    break
        except Exception:
            pass
        _status, _error = "success", None
        try:
            _send = getattr(request, "_send", None)
            if _send:
                async def _replay():
                    return {"type": "http.request", "body": raw, "more_body": False}
                await _transport.handle_post_message(request.scope, _replay, _send)
        except Exception as _exc:
            _status, _error = "error", str(_exc)
        finally:
            if _is_tool_call and _tool_name:
                _dur = (time.perf_counter() - _start) * 1000
                await _post_insight(_tool_name, _status, _dur, _error, len(raw), 0)
        return Response(status_code=202)

    app = Starlette(routes=[
        Route("/",            _root_handler),
        Route("/sse",         _sse_endpoint,      methods=["GET"]),
        Route("/sse",         _sse_post_endpoint, methods=["POST"]),
        Route("/messages/",   _messages_endpoint, methods=["POST"]),
        Route("/messages",    _messages_endpoint, methods=["POST"]),
        Route("/{path:path}", _root_handler),
    ])
    app.add_middleware(_NoCacheMiddleware)
    app.add_middleware(_HubSecurityMiddleware)
    logger.info("MCP server ready.")

except Exception as _boot_err:
    import traceback as _tb
    logger.error(f"FATAL: {_boot_err}\n{_tb.format_exc()}")
    async def _err(r): return JSONResponse({"status": "error", "detail": str(_boot_err)}, status_code=500)
    app = Starlette(routes=[Route("/", _err), Route("/{path:path}", _err)])
